routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('funcionarios', 'FuncionarioController');

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Funcionario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Funcionario extends Model
{
    protected $fillable = ['matricula', 'salario'];

    public function pessoa(){
        return $this->belongsTo('App\Pessoa', 'id_pessoa');
    }
}

app/Pessoa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pessoa extends Model
{
       protected $fillable = ['cpf', 'nome', 'email', 'telefone'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FuncionarioController.php
<?php

namespace App\Http\Controllers;

use App\Funcionario;
use App\Console\Commands\CreateFuncionarioCommand;
use App\Console\Commands\EditFuncionarioCommand;
use App\Console\Commands\DeleteFuncionarioCommand;
use Illuminate\Http\Request;
use Illuminate\Foundation\Bus\DispatchesCommands;
use Session;

class FuncionarioController extends Controller
{
    /**
     * Exibe a lista de funcionários.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $funcionarios = Funcionario::all();

        return view('funcionarios.index')->with('funcionarios', $funcionarios);
    }

    /**
     * Mostra o formulário de criação.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('funcionarios.create');
    }

    /**
     * Armazena um novo funcionário.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'cpf' => 'required|max:11|unique:pessoas,cpf',   
            'nome' => 'required|string|max:255',
            'email' => 'required|string|email|max:255',
            'telefone' => 'required|max:11|',   
            'matricula' => 'required|max:6|unique:funcionarios,matricula,',
            'salario' => 'required|numeric',   
        ]);

        $funcionario = new Funcionario();

        $dados = array();
        $dados['cpf'] = $request->cpf;
        $dados['nome'] = $request->nome;
        $dados['email'] = $request->email;
        $dados['telefone'] = $request->telefone;
        $dados['matricula'] = $request->matricula;
        $dados['salario'] = $request->salario;

        //Chamada do comando:
        $this->dispatch(
            new CreateFuncionarioCommand($funcionario, $dados)
        );

        Session::flash('sucesso', 'Funcionário cadastrado.');

        return redirect()->route('funcionarios.index');
    }

    /**
     * Exibe o funcionário.
     *
     * @param  \App\Funcionario  $funcionario
     * @return \Illuminate\Http\Response
     */
    public function show(Funcionario $funcionario)
    {
        return view('funcionarios.show')->with('funcionario', $funcionario);
    }

    /**
     * Mostra o formulário de edição do funcionário.
     *
     * @param  \App\Funcionario  $funcionario
     * @return \Illuminate\Http\Response
     */
    public function edit(Funcionario $funcionario)
    {
        return view('funcionarios.edit')->with('funcionario', $funcionario);
    }

    /**
     * Atualiza o funcionário.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Funcionario  $funcionario
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Funcionario $funcionario)
    {    
        $request->validate([
            'cpf' => 'required|max:11|unique:pessoas,cpf,'.$funcionario->pessoa->id,   
            'nome' => 'required|string|max:255',
            'email' => 'required|string|email|max:255',
            'telefone' => 'required|max:11|',   
            'matricula' => 'required|max:6|unique:funcionarios,matricula,'.$funcionario->id,
            'salario' => 'required|numeric',   
        ]);

        $dados = array();
        $dados['cpf'] = $request->cpf;
        $dados['nome'] = $request->nome;
        $dados['email'] = $request->email;
        $dados['telefone'] = $request->telefone;
        $dados['matricula'] = $request->matricula;
        $dados['salario'] = $request->salario;

        //Chamada do comando:
        $this->dispatch(
            new EditFuncionarioCommand($funcionario, $dados)
        );

        Session::flash('sucesso', 'Funcionário editado.');

        return redirect()->route('funcionarios.index');
    }

    /**
     * Deleta o funcionário.
     *
     * @param  \App\Funcionario  $funcionario
     * @return \Illuminate\Http\Response
     */
    public function destroy(Funcionario $funcionario)
    {
        //Chamada do comando:
        $this->dispatch(
            new DeleteFuncionarioCommand($funcionario)
        );

        Session::flash('sucesso', 'Funcionário deletado.');

        return redirect()->route('funcionarios.index');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/funcionarios/create.blade.php
@extends('principal')

@section('conteudo')

	<div class="container">

		<br>

		<h3 class="text-center"> <b>CADASTRAR FUNCIONÁRIO</h3>
		<br>

		<form action="{{route('funcionarios.store')}}" method="POST" onsubmit="doSubmit()">

			{{ csrf_field() }}

			<div class="form-row">

				<div class="form-group col-md-4">

					<label for="cpf"><b>CPF:</b></label>
		      		<input type="text" class="form-control" id="cpf" name="cpf" placeholder="Informe o CPF" value="{{old('cpf')}}" required="">

				</div>

				<div class="form-group col-md-4">
					<label for="nome"><b>Nome:</b></label>
			      	<input type="text" class="form-control" id="nome" name="nome" placeholder="Informe o nome" value="{{old('nome')}}" required="">
				</div>

				<div class="form-group col-md-4">
					<label for="nome"><b>E-mail:</b></label>
			      	<input type="email" class="form-control" id="email" name="email" placeholder="Informe o e-mail" value="{{old('email')}}" required="">
				</div>


			</div>		

			<div class="form-row">

				<div class="form-group col-md-4">
					<label for="telefone"><b>Telefone:</b></label>
			      	<input type="text" class="form-control" id="telefone" name="telefone" placeholder="Informe o telefone" value="{{old('telefone')}}" required="">
				</div>

				<div class="form-group col-md-4">
					<label for="matricula"><b>Matrícula:</b></label>
			      	<input type="matricula" class="form-control" id="matricula" name="matricula" placeholder="Informe a matrícula" value="{{old('matricula')}}" required="">
				</div>

				<div class="form-group col-md-4">

					<label for="salario"><b>Salário:</b></label>
		      		<input type="text" class="form-control" id="salario" name="salario" placeholder="Informe o salário" value="{{old('salario')}}" required="">

				</div>


			</div>		

			<br>
		 	<button type="submit" class="btn btn-lg btn-block tema-desempenho">Cadastrar</button>

		</form>

		<br><br><br>
		  
	</div>

@endsection


@section('scripts')

	<script src="/js/jquery.mask.min.js"></script>

	<script type="text/javascript">
		function doSubmit(){
			$('#cpf').unmask();
			$('#telefone').unmask();
		  	return true;
		}
	</script>

	 <script type="text/javascript">
	 	$(document).ready(function(){
  			$('#cpf').mask('999.999.999-99');
  			$('#telefone').mask('(99) 99999-9999');
		});
	 </script>

@endsection

resources/views/funcionarios/edit.blade.php
@extends('principal')

@section('conteudo')

	<div class="container">

		<br>

		<h3 class="text-center"> <b>EDITAR FUNCIONÁRIO</h3>
		<br>

		<form action="{{route('funcionarios.update', $funcionario)}}" method="POST" onsubmit="doSubmit()">

			{{ csrf_field() }}
		
			<input name="_method" type="hidden" value="PUT">

			<div class="form-row">

				<div class="form-group col-md-4">

					<label for="cpf"><b>CPF:</b></label>
		      		<input type="text" class="form-control" id="cpf" name="cpf" placeholder="Informe o CPF" value="{{$funcionario->pessoa->cpf}}" required="">

				</div>

				<div class="form-group col-md-4">
					<label for="nome"><b>Nome:</b></label>
			      	<input type="text" class="form-control" id="nome" name="nome" placeholder="Informe o nome" value="{{$funcionario->pessoa->nome}}" required="">
				</div>

				<div class="form-group col-md-4">
					<label for="nome"><b>E-mail:</b></label>
			      	<input type="email" class="form-control" id="email" name="email" placeholder="Informe o e-mail" value="{{$funcionario->pessoa->email}}" required="">
				</div>


			</div>		

			<div class="form-row">

				<div class="form-group col-md-4">
					<label for="telefone"><b>Telefone:</b></label>
			      	<input type="text" class="form-control" id="telefone" name="telefone" placeholder="Informe o telefone" value="{{$funcionario->pessoa->telefone}}" required="">
				</div>

				<div class="form-group col-md-4">
					<label for="matricula"><b>Matrícula:</b></label>
			      	<input type="matricula" class="form-control" id="matricula" name="matricula" placeholder="Informe a matrícula" value="{{$funcionario->matricula}}" required="">
				</div>

				<div class="form-group col-md-4">

					<label for="salario"><b>Salário:</b></label>
		      		<input type="text" class="form-control" id="salario" name="salario" placeholder="Informe o salário" value="{{$funcionario->salario}}" required="">

				</div>


			</div>		

			<br>
		 	<button type="submit" class="btn btn-lg btn-block tema-desempenho">Editar</button>

		</form>

		<br><br><br>
		  
	</div>

@endsection


@section('scripts')

	<script src="/js/jquery.mask.min.js"></script>

	<script type="text/javascript">
		function doSubmit(){
			$('#cpf').unmask();
			$('#telefone').unmask();
		  	return true;
		}
	</script>

	 <script type="text/javascript">
	 	$(document).ready(function(){
  			$('#cpf').mask('999.999.999-99');
  			$('#telefone').mask('(99) 99999-9999');
		});
	 </script>

@endsection

resources/views/funcionarios/index.blade.php
@extends('principal')

@section('conteudo')
	
	<div class="container">
			
			<br><br>
			<h2> Funcionários </h2>

			<br><br>

			<div class="card">
			  	<div class="card-header">
				  	<div class="row"> 
				  		<div class="col-md-6">	
						    
				  		</div>
				  		<div class="col-md-6">
				  		  <button onclick="window.location='{{ route('funcionarios.create')}}'" type="button" data-toggle="tooltip" title = "Cadastrar Funcionário" class="btn btn-lg btn-secondary float-right"><i class="fa fa-plus"></i></button>	
				  		</div>
				  	</div>
		  		</div>

			  	<div class="card-body">
					
					<table class="table">

				  		<thead>
						    <tr>
						      <th scope="col">#</th>
							  <th scope="col">Nome</th>
							  <th scope="col">CPF</th>
							  <th scope="col">E-mail</th>
							  <th scope="col">Telefone</th>
							  <th scope="col">Matrícula</th>
							  <th scope="col">#</th>
							  <th scope="col">#</th>
							  <th scope="col">#</th>
						    </tr>
					  	</thead>
					
					  <tbody>

					  	@php
					  		$i = 1;
					  	@endphp

						@foreach($funcionarios as $funcionario)

							    <tr>
							      	
							      	<th scope="row">{{$i}}</th>
							      	<td> <p>{!! $funcionario->pessoa->nome !!}</p> </td>
							      	<td> <p>{!! $funcionario->pessoa->cpf !!}</p> </td>
							      	<td> <p>{!! $funcionario->pessoa->email !!}</p> </td>
							      	<td> <p>{!! $funcionario->pessoa->telefone !!}</p> </td>
							      	<td> <p>{!! $funcionario->matricula !!}</p> </td>
							      	
							    	<td>
										<button onclick="window.location='{{ route('funcionarios.show', $funcionario)}}'" type="button" data-toggle="tooltip" title = "Editar" class="btn silver-gray"><i class="fa fa-eye"></i></button>
									</td>

							      	<td>
										<button onclick="window.location='{{ route('funcionarios.edit', $funcionario)}}'" type="button" data-toggle="tooltip" title = "Editar" class="btn silver-gray"><i class="fa fa-edit"></i></button>
									</td>

									<td>
										<form action="{{route('funcionarios.destroy', $funcionario->id)}}" method="POST" onsubmit="return confirm('Tem certeza que deseja deletar este item?')">
						
											{{ csrf_field() }}

											<!-- needed to use DELETE method -->
											<input name="_method" type="hidden" value="DELETE">

											<button type="submit" data-toggle="tooltip" title = "Deletar" class="btn silver-gray"><i class="fa fa-trash"></i></button>
									
										</form>
									</td>

							    </tr>

					  	@php
					  		$i++;
					  	@endphp

						@endforeach

					  </tbody>
					</table>


				</div>

		</div>

	</div>

@endsection

resources/views/funcionarios/show.blade.php
@extends('principal')

@section('conteudo')

	<div class="container">
		
		<br>

		<h3 class="text-center"> <b>VISUALIZAR FUNCIONÁRIO</h3>
		<br>

		<div class="row">

			<div class="col-sm">

				<div class="card">
				  <div class="card-header tema-desempenho2">
				 	<b>Informações Pessoais</b>
				  </div>
				  <div class="card-body tema-desempenho">
				    
				    <h6 ><b>Nome:</b></h6>
				    <p>{{ $funcionario->pessoa->nome }}</p>

				    <h6 ><b>CPF:</b></h6>
				    <p> {{ empty($funcionario->pessoa->cpf) ? "---" : \App\Classes\Exibicao\Mascara::aplica($funcionario->pessoa->cpf, "###.###.###-##") }}</p>

				    <h6 ><b>E-mail:</b></h6>
				    <p>{{ $funcionario->user != null ? $funcionario->user->email : "---"}}</p>

				    <h6 ><b>Telefone:</b></h6>
				    <p> {{ empty($funcionario->pessoa->telefone) ? "---" : \App\Classes\Exibicao\Mascara::aplica($funcionario->pessoa->telefone, "(##) #####-####") }}</p>
				 
				  </div>
				</div>
			</div>

			<div class="col-sm">

				<div class="card">
				  <div class="card-header tema-desempenho2">
				 	<b>Informações do Funcionário</b>
				  </div>
				  <div class="card-body tema-desempenho">
				    
				    <h6 ><b>Matrícula:</b></h6>
				    <p>{{ $funcionario->matricula }}</p>

				    <h6 ><b>Salario:</b></h6>
				    <p> {{ $funcionario->salario }}</p>

				  </div>
				</div>
			</div>
		</div>

	</div>

@endsection

resources/views/home.blade.php
@extends('principal')

@section('conteudo')
	
	<div class="container">
			
			
		<div class="jumbotron jumbotron-fluid">
		  <div class="container">
		    <h1 class="display-4">FX</h1>
		    <p class="lead"> Sistema de Gerenciamento de Funcionários </p>
		  </div>
		</div>

	</div>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'FX') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'FX') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Registrar') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/parciais/_head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>@yield('titulo')</title>

<!-- Bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!--
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
-->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

resources/views/parciais/_login.blade.php
  @if(Auth::check())


  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">{{ csrf_field() }}</form>

  <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Bem-vindo {{ Auth::user()->name }}
      </a>


      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Sair</a>
      </div>
  </li>

      <li class="nav-item">
          <a class="nav-link" href="{{ url('/register') }}">Registrar</a>
      </li>

  
  
  
  @else

  <li class="nav-item">
      <a class="nav-link" href="{{ url('/login') }}">Login</a>
  </li>

  @endif

resources/views/parciais/_mensagens.blade.php
@if(Session::has('sucesso'))

	<div class="alert alert-success" role="alert">
		<strong>Sucesso: </strong> {{ Session::get('sucesso')}}
	</div>

@endif

@if(Session::has('erro'))

	<div class="alert alert-danger" role="alert">
		<strong>Erro: </strong> {{ Session::get('erro')}}
	</div>

@endif

@if(count($errors) > 0)

	<div class="alert alert-danger" role="alert">
		<strong>Erros:</strong>
		<ul>
		@foreach($errors->all() as $error)
			<li> {{ $error }} </li>
		@endforeach
		</ul>
	</div>

@endif

resources/views/parciais/_navegacao.blade.php
<div class="container">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">FX</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{{route('funcionarios.index')}}">Funcionários <span class="sr-only">(current)</span></a>
        </li>

    </ul>
      <ul class="navbar-nav">

          @include('parciais._login')

      </ul>
    </div>
  </nav>

</div>

resources/views/parciais/_rodape.blade.php
<footer class="mt-5">

  <p class="text-center"> FX | Copyright © 2019 | Todos os direitos reservados | v1.0  </p>

</footer>

resources/views/principal.blade.php
<!DOCTYPE html>
<html lang="pt-br">

  <head>

  	@include('parciais._head')

    @yield('scripts')
    @yield('stylesheets')
  </head>
  
  <body style="font-family: verdana;">

    <div class="container">

        @include('parciais._navegacao')

        @include('parciais._mensagens')

  	    @yield('conteudo')

  	    @include('parciais._rodape')
      	    
      </div>
  </body>
</html>